config/routes.rb
Capstone::Application.routes.draw do
  devise_for :businesses

  resources :businesses

  devise_for :users, :controllers => {:registrations => "registrations"}
  match '/search' => 'Businesses#search', :as => :search
  match '/' => 'Application#home', :as => :root
  match '/valentinos' => 'Businesses#valentinos'

end

app/models/business.rb
class Business < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :address, :description, :email, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body, :email, :password, :password_confirm
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def home
    
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @businesses }
    end
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
    @business = Business.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @business }
    end
  end

  # GET /businesses/new
  # GET /businesses/new.json
  def new
    @business = Business.new
    @user = User.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @business }
    end
  end

  def valentinos
  
  end
  # GET /businesses/1/edit
  def edit
    @business = Business.find(params[:id])
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(params[:business])

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render json: @business, status: :created, location: @business }
      else
        format.html { render action: "new" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /businesses/1
  # PUT /businesses/1.json
  def update
    @business = Business.find(params[:id])

    respond_to do |format|
      if @business.update_attributes(params[:business])
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business = Business.find(params[:id])
    @business.destroy

    respond_to do |format|
      format.html { redirect_to businesses_url }
      format.json { head :no_content }
    end
  end
  def search

  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new_business
    resource = build_resource({})
    @business = Business.new
    respond_with resource
  end
  
  def new
    super
  end
  # POST /resource
  def create
    build_resource
    @business = Business.new(params[:business])
    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_up(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/application/home.html.erb
    <script>
      $(document).ready(function(){
        $('.carousel').carousel({
          interval: 10000
        });
      });
    </script>


    
<div style="clear:both; float:left;"><h1 style="margin-top: 0px; margin-bottom: 10px; ">Welcome to BizHub!</h1></div>

<div id="user_nav" style="float:right; margin-top:-10px;">
    <% if user_signed_in? %>
      Signed in as <%= current_user.email %>. Not you?
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
    <% end %>
</div>

      <!--  Carousel -->
      <!--  consult Bootstrap docs at 
            http://twitter.github.com/bootstrap/javascript.html#carousel -->
      <div id="this-carousel-id" class="carousel slide"> 
        <div class="carousel-inner">
          <div class="item active" style="background-image:url(<%=asset_path "store.png"%>); height: 350px; margin-top: 40px;">
          	<div style="margin-left:120px; margin-top: 40px; clear:both; float: left;">
            	<h1 id="carouselheader" style="margin-bottom: 10px;">Businesses</h1>
                <div style="margin-left:25px;">
                    <h2>Sell</h2><h5 style="text-indent: 15px;"> ...your goods and services directly through BizHub</h5><br />
                    <h2>Reach</h2><h5 style="text-indent: 15px;"> ...new customers through your BizPage profile</h5><br />
                    <h2>Offer</h2><h5 style="text-indent: 15px;"> ...all your goods and services through the easy-to-use Menu</h5><br />
                    <form method="get" action="<%=new_user_registration_path%>"> <button type="submit" class="btn btn-primary"><h3 style="color:#FFF; margin-left:10px; margin-right:10px;">Sign Up</h3></button></form>
             	</div>
            </div>
          </div>
          <div class="item" style="background-image:url(<%=asset_path "woman.png"%>); height: 350px; margin-top: 40px;">
            <div style="margin-right:90px; margin-top: 50px; clear:both; float: right;">
            	<h1 id="carouselheader" style="margin-bottom: 10px;">Customers</h1>
                <div style="margin-left:25px;">
                    <h2>Buy</h2><h5 style="text-indent: 15px;"> ...your favorite goods and services fast and easy</h5><br />
                    <h2>Search</h2><h5 style="text-indent: 15px;"> ...for new businesses based on your current location</h5><br />
                    <h2>Pay</h2><h5 style="text-indent: 15px;"> ...automatically through your Google Wallet account</h5><br />
                    <form method="get" action="<%=new_user_registration_path%>"> <button type="submit" class="btn btn-primary"><h3 style="color:#FFF; margin-left:10px; margin-right:10px;">Sign Up</h3></button></form>
             	</div>
            </div>
          </div>
        </div><!-- .carousel-inner -->
        <!--  next and previous controls here
              href values must reference the id for this carousel -->
          <a class="carousel-control left" href="#this-carousel-id" data-slide="prev">&lsaquo;</a>
          <a class="carousel-control right" href="#this-carousel-id" data-slide="next">&rsaquo;</a>
      </div><!-- .carousel -->
      <!-- end carousel -->
      
      <div class="row" style="border-radius: 3px; background-image:url(<%=asset_path "rowBG.png"%>); background-repeat:repeat-x; background-size: auto 100%; width: 980px;">
        <div class="span4">
          <h2>Simple.</h2>
           <p style="text-indent:15px;">Search for any business, product, or service to find what you want.  Select your purchase using the easy-to-use menu displaying all that the business has to offer, then checkout with a single click!</p>
          <p><a class="btn btn-primary" href="#">Learn More &raquo;</a></p>
        </div>
        <div class="span4">
          <h2>Convenient.</h2>
           <p style="text-indent:15px;">Order food for pickup or delivery.  Schedule appointments for whatever task you need.  Order anything from local stores, restaurants, and services.  Shop and pay directly from you computer or mobile device!</p>
          <p><a class="btn btn-primary" href="#">Learn More &raquo;</a></p>
       </div>
        <div class="span4">
          <h2>Safe.</h2>
          <p style="text-indent:15px;">Using your Google Wallet account, your information is kept secure and will never be compromised.  You can easily manage your past transactions and keep track of what your have purchased.</p>
          <p><a class="btn btn-primary" href="#">Learn More &raquo;</a></p>
        </div>
      </div>

      <hr>

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
<div width="600px">
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= fields_for(@user, :as => @user) do |fa| %>

  <div><%= fa.label :email %><br />
  <%= fa.email_field :email, :autofocus => true %></div>

  <div><%= fa.label :password %><br />
  <%= fa.password_field :password %></div>

  <div><%= fa.label :password_confirmation %><br />
  <%= fa.password_field :password_confirmation %></div>

<% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_area :email %>
  </div>
  

  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<h1>Listing businesses</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Description</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @businesses.each do |business| %>
  <tr>
    <td><%= business.name %></td>
    <td><%= business.address %></td>
    <td><%= business.description %></td>
    <td><%= business.email %></td>
    <td><%= link_to 'Show', business %></td>
    <td><%= link_to 'Edit', edit_business_path(business) %></td>
    <td><%= link_to 'Destroy', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<h1>New business</h1>

<%= render 'form' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/search.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
<br /><br /><br /><br />
<%= params.to_s %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @business.name %>
</p>

<p>
  <b>Address:</b>
  <%= @business.address %>
</p>

<p>
  <b>Description:</b>
  <%= @business.description %>
</p>

<p>
  <b>Email:</b>
  <%= @business.email %>
</p>


<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/valentinos.html.erb
<div class="container" style="margin-top:100px; width:940px;">

	
    <div id="contentDiv">
    	<img id="bizPic" src="profilePic.jpg" />
        
        <div id="bizInfo">
        	<h1 style="margin-bottom: 10px; float:left;">Valentino's Pizza</h1>
            <form style="float:right;" action="#">
            	<button type="submit" class="btn btn-primary"><h3 style="color:#FFF; margin-left:10px; margin-right:10px;">Enter Menu</h3></button>
            </form>
            <div style="clear:left; width: 47px; float:left; overflow:hidden; margin-right: 10px;">
            	<div class="fb-like" data-send="false" data-width="150" data-show-faces="false" style="width:47px;"></div>
            </div>
            <div style="width: 38px; float:left; overflow:hidden; margin-right: 10px;">
            	<g:plusone annotation="inline" width="150"></g:plusone> 
            </div>
            <div style="width: 60px; float:left; overflow:hidden; margin-right: 10px;">
            	<a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
            </div>
            <hr style="clear:both;" />
            <h4 style="clear:both; margin-bottom: 15px;">
            	2197 Murray Hill Rd<br />
                Cleveland, OH 44106<br />
                (216) 795-0463<br />
          	</h4>
            <p style="clear:both;">
            	Located on Murray Hill in the historic Little Italy district, Valentino's serves the best thin crust pizza around.  Enjoy our specialty pizzas in our patio dining area or get an order delivered to your home.  We have many subs, salads, and desserts as well.  
          	</p>
      	</div>
	</div>    

app/views/layouts/application.html.erb
  

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>Capstone</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>


</head>
  <style>
    body {
      margin: 0;
      font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
      font-size: 13px;
      line-height: 18px;
      color: #333333;
      background-color: #ffffff;
      background-image:url(<%=asset_path "cityBG.png"%>);
      background-repeat:no-repeat;
      background-position: 0% 100%;
      background-attachment:fixed;
      background-size: 100% auto;
    }
</style>
  
<body>





<!-- FACEBOOK LIKE STUFF -->

<div id="fb-root"></div>  
<script>(function(d, s, id) {  
  var js, fjs = d.getElementsByTagName(s)[0];  
  if (d.getElementById(id)) return;  
  js = d.createElement(s); js.id = id;  
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1";  
  fjs.parentNode.insertBefore(js, fjs);  
}(document, 'script', 'facebook-jssdk'));</script>  

<!-- FACEBOOK LIKE STUFF - END -->




<!-- Nav Bar Div Start -->

<div class="navbar navbar-fixed-top">  				
  <div class="navbar-inner">  
    <div class="container">  
    <ul class="nav">  
  <li>  
    <a class="brand" href="#"><img src='<%=asset_path "bizhub.png"%>' alt="BizHub" style="height: 20px; margin-right: 50px;" /></a>  
  </li>  
  <li><%= link_to "Home",    '/' %></li>
              <li class="dropdown">
                  <a class="dropdown-toggle" id="dLabel" data-toggle="dropdown" href ='#'>New Account<b class="caret"></b></a>
                  <ul class="dropdown-menu" role='menu'  aria-labelledby="dLabel">
                    <li><%= link_to 'New Business', '/businesses/sign_up' %></li>
                    <li><%= link_to 'New Customer', '/users/sign_up' %></li>
                  </ul>
              </li>
              <li class="dropdown">
                  <a class="dropdown-toggle" id="dLabel" data-toggle="dropdown" href ='#'>Log In<b class="caret"></b></a>
                  <ul class="dropdown-menu" role='menu'  aria-labelledby="dLabel">
                    <li><a href="/businesses/sign_in">Business</a></li>
                    <li><a href="/users/sign_in">Customer</a></li>
                  </ul>
              </li>
  <li><a href="#">Contact</a></li>  
</ul>  
<ul class="nav">  
  <li class="dropdown">  
    <a href="#"  
          class="dropdown-toggle"  
          data-toggle="dropdown">  
          Services  
          <b class="caret"></b>  
    </a>  
    <ul class="dropdown-menu">  
     <li><a href="#">Web Design</a></li>  
  <li><a href="#">Web development</a></li>  
  <li><a href="#">Wordpress Theme development</a></li>  
    </ul>  
  </li>  
</ul>  
﻿<form class ="navbar-search pull-right"accept-charset="UTF-8" action="search" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="NEc8Zswj61T+Zhj8gcWtIgCbgghd2fpA0rPc2LWWiIs=" /></div>
  <input type="text" class="search-query" placeholder="Search" id="searchParam" name="searchParam">
  <input type="submit" style="position: absolute; left: -9999px; width: 1px; height: 1px;"/>
</form>  
<ul class="nav pull-right">  
  <li class="dropdown">  
    <a href="#"  
          class="dropdown-toggle"  
          data-toggle="dropdown">  
          Social  
          <b class="caret"></b>  
    </a>  
    <ul class="dropdown-menu">  
     <li class="socials"><!-- Place this tag where you want the +1 button to render -->  
<g:plusone annotation="inline" width="150"></g:plusone>  
</li>  
  <li class="socials"><div class="fb-like" data-send="false" data-width="150" data-show-faces="true"></div></li>  
  <li class="socials"><a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>  
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script></li>  
    </ul>  
  </li>  
</ul>  
    </div>  
  </div>
  
</div>  
<script type="text/javascript">  
  (function() {  
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;  
    po.src = 'https://apis.google.com/js/plusone.js';  
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);  
  })();  
</script>
<div class="container" style="margin-top:60px; width:940px;">
      <%if(notice != nil)%>
      <p class="notice"><%= notice %></p>
      <%end%>
      <%if(alert != nil)%>
       <p class="alert"><%= alert %></p> 
       <%end%>
    <%= yield %>

      <br /><br />
      <footer>
        <p>By <a href="http://twitter.com/davidcochran">David Cochran</a> of <a href="http://alittlecode.com/">aLittleCode.com</a> for <a href="http://webdesign.tutsplus.com/">webdesign.tutsplus.com</a></p>
      </footer>

    </div> <!-- /container -->
</body>
</html>